# print jokes
print('Apa persamaan tukang siomay dan tukang empek2?')
input()
print('Sama sama gak jualan nasi goreng !')
input()
print('Apa itu cemilan?')
input()
print('cecudah celapan, cebelum cepuluh !')
input()
print('Ayam apa yang bikin kesel?')
input()
print('Ayamnya habis, nasinya masih banyak !')
input()
print('Kenapa gunung api meletus?')
input()
print('Karena kalau mencair namanya Gunung Es!')
input()
print('Udah, segitu dulu aja! Marfu\'ah capek !')